vars: {
    d2-config: {
      layout-engine: dagre
      theme-id: 300
    }
  }
  
  network: {
    Frontend Service: {region: "A"}
    API Gateway: {region: "A"}
    Microservice 1: Data Storage: {region: "A"}
    Microservice 2: Message Publisher: {region: "A"}
    SNS Topic: {region: "A"}
    AWS Lambda Function: {region: "B"}
    DynamoDB Table: {region: "B"}
    S3 Bucket: {region: "A"}
    Redis Cache: {region: "B"}
  
    Frontend Service -> API Gateway: send requests
    API Gateway -> Microservice 1: store data
    API Gateway -> Microservice 2: publish messages
    Microservice 1 -> DynamoDB Table: store data
    Microservice 2 -> SNS Topic: publish messages
    SNS Topic -> AWS Lambda Function: trigger
    AWS Lambda Function -> DynamoDB Table: update data
    Frontend Service -> S3 Bucket: retrieve static content
    Frontend Service -> Redis Cache: store session information
  }